### ISSUE TITLE
Matrix rank () return the wrong rank of a complex matrix  

### ISSUE THREAD

**Issue by adukova** [sympy/sympy#16823]
There is an error in the Matrix.rank() function.
The rank of the following matrix T should be 8.
`T = Matrix([[S('1+I'),S('-19/4+5/4*I'),S('1/2-I'),S('9/4+55/16*I'),S('-3/4'),S('45/32-37/16*I'),S('1/4+1/2*I'),S('-129/64-9/64*I'),S('1/4-5/16*I'),S('65/128+87/64*I'),S('-9/32-1/16*I'),S('183/256-97/128*I'),S('3/64+13/64*I'),S('-23/32-59/256*I'),S('15/128-3/32*I'),S('19/256+551/1024*I')],[S('21/8+I'),S('-537/64+143/16*I'),S('-5/8-39/16*I'),S('2473/256+137/64*I'),S('-149/64+49/32*I'),S('-177/128-1369/128*I'),S('125/64+87/64*I'),S('-2063/256+541/128*I'),S('85/256-33/16*I'),S('805/128+2415/512*I'),S('-219/128+115/256*I'),S('6301/4096-6609/1024*I'),S('119/128+143/128*I'),S('-10879/2048+4343/4096*I'),S('129/256-549/512*I'),S('42533/16384+29103/8192*I')],[S('-2'),S('17/4-13/2*I'),S('1+I'),S('-19/4+5/4*I'),S('1/2-I'),S('9/4+55/16*I'),S('-3/4'),S('45/32-37/16*I'),S('1/4+1/2*I'),S('-129/64-9/64*I'),S('1/4-5/16*I'),S('65/128+87/64*I'),S('-9/32-1/16*I'),S('183/256-97/128*I'),S('3/64+13/64*I'),S('-23/32-59/256*I')],[S('1/4+13/4*I'),S('-825/64-147/32*I'),S('21/8+I'),S('-537/64+143/16*I'),S('-5/8-39/16*I'),S('2473/256+137/64*I'),S('-149/64+49/32*I'),S('-177/128-1369/128*I'),S('125/64+87/64*I'),S('-2063/256+541/128*I'),S('85/256-33/16*I'),S('805/128+2415/512*I'),S('-219/128+115/256*I'),S('6301/4096-6609/1024*I'),S('119/128+143/128*I'),S('-10879/2048+4343/4096*I')],[S('-4*I'),S('27/2+6*I'),S('-2'),S('17/4-13/2*I'),S('1+I'),S('-19/4+5/4*I'),S('1/2-I'),S('9/4+55/16*I'),S('-3/4'),S('45/32-37/16*I'),S('1/4+1/2*I'),S('-129/64-9/64*I'),S('1/4-5/16*I'),S('65/128+87/64*I'),S('-9/32-1/16*I'),S('183/256-97/128*I')],[S('1/4+5/2*I'),S('-23/8-57/16*I'),S('1/4+13/4*I'),S('-825/64-147/32*I'),S('21/8+I'),S('-537/64+143/16*I'),S('-5/8-39/16*I'),S('2473/256+137/64*I'),S('-149/64+49/32*I'),S('-177/128-1369/128*I'),S('125/64+87/64*I'),S('-2063/256+541/128*I'),S('85/256-33/16*I'),S('805/128+2415/512*I'),S('-219/128+115/256*I'),S('6301/4096-6609/1024*I')],[S('-4'),S('9-5*I'),S('-4*I'),S('27/2+6*I'),S('-2'),S('17/4-13/2*I'),S('1+I'),S('-19/4+5/4*I'),S('1/2-I'),S('9/4+55/16*I'),S('-3/4'),S('45/32-37/16*I'),S('1/4+1/2*I'),S('-129/64-9/64*I'),S('1/4-5/16*I'),S('65/128+87/64*I')],[S('-2*I'),S('119/8+29/4*I'),S('1/4+5/2*I'),S('-23/8-57/16*I'),S('1/4+13/4*I'),S('-825/64-147/32*I'),S('21/8+I'),S('-537/64+143/16*I'),S('-5/8-39/16*I'),S('2473/256+137/64*I'),S('-149/64+49/32*I'),S('-177/128-1369/128*I'),S('125/64+87/64*I'),S('-2063/256+541/128*I'),S('85/256-33/16*I'),S('805/128+2415/512*I')],[S('0'),S('-6'),S('-4'),S('9-5*I'),S('-4*I'),S('27/2+6*I'),S('-2'),S('17/4-13/2*I'),S('1+I'),S('-19/4+5/4*I'),S('1/2-I'),S('9/4+55/16*I'),S('-3/4'),S('45/32-37/16*I'),S('1/4+1/2*I'),S('-129/64-9/64*I')],[S('1'),S('-9/4+3*I'),S('-2*I'),S('119/8+29/4*I'),S('1/4+5/2*I'),S('-23/8-57/16*I'),S('1/4+13/4*I'),S('-825/64-147/32*I'),S('21/8+I'),S('-537/64+143/16*I'),S('-5/8-39/16*I'),S('2473/256+137/64*I'),S('-149/64+49/32*I'),S('-177/128-1369/128*I'),S('125/64+87/64*I'),S('-2063/256+541/128*I')],[S('0'),S('-4*I'),S('0'),S('-6'),S('-4'),S('9-5*I'),S('-4*I'),S('27/2+6*I'),S('-2'),S('17/4-13/2*I'),S('1+I'),S('-19/4+5/4*I'),S('1/2-I'),S('9/4+55/16*I'),S('-3/4'),S('45/32-37/16*I')],[S('0'),S('1/4+1/2*I'),S('1'),S('-9/4+3*I'),S('-2*I'),S('119/8+29/4*I'),S('1/4+5/2*I'),S('-23/8-57/16*I'),S('1/4+13/4*I'),S('-825/64-147/32*I'),S('21/8+I'),S('-537/64+143/16*I'),S('-5/8-39/16*I'),S('2473/256+137/64*I'),S('-149/64+49/32*I'),S('-177/128-1369/128*I')]])
Result; rank= 9 time: 11558.603042602539`
Matrix rank() and matrix rank(simplify=True) produce the wrong result 9.
Moreover, this function takes too much time (library gmpy2 installed).

**Comment by oscarbenjamin** [comment]
The slowness is because of expression blowup.

Even though all numbers are of the form `q1 + I*q2` for rationals q1 and q2 we end up with large expressions. Here's what happens just using the top 5 rows and columns from the (12x12) matrix:
```julia
In [26]: T[:5, :5]                                                                                                                                                                                                 
Out[26]: 
⎡             19   5⋅ⅈ                  9   55⋅ⅈ                 ⎤
⎢ 1 + ⅈ     - ── + ───     1/2 - ⅈ      ─ + ────         -3/4    ⎥
⎢             4     4                   4    16                  ⎥
⎢                                                                ⎥
⎢            537   143⋅ⅈ    5   39⋅ⅈ  2473   137⋅ⅈ     149   49⋅ⅈ⎥
⎢21/8 + ⅈ  - ─── + ─────  - ─ - ────  ──── + ─────   - ─── + ────⎥
⎢             64     16     8    16   256      64       64    32 ⎥
⎢                                                                ⎥
⎢            17   13⋅ⅈ                   19   5⋅ⅈ                ⎥
⎢   -2       ── - ────      1 + ⅈ      - ── + ───      1/2 - ⅈ   ⎥
⎢            4     2                     4     4                 ⎥
⎢                                                                ⎥
⎢1   13⋅ⅈ    825   147⋅ⅈ                537   143⋅ⅈ     5   39⋅ⅈ ⎥
⎢─ + ────  - ─── - ─────   21/8 + ⅈ   - ─── + ─────   - ─ - ──── ⎥
⎢4    4       64     32                  64     16      8    16  ⎥
⎢                                                                ⎥
⎢                                       17   13⋅ⅈ                ⎥
⎢  -4⋅ⅈ     27/2 + 6⋅ⅈ        -2        ── - ────       1 + ⅈ    ⎥
⎣                                       4     2                  ⎦

In [27]: t, _ = T[:5, :5].rref()                                                                                                                                                                                   

In [28]: t.expand()                                                                                                                                                                                                
Out[28]: 
⎡             9395686579   2610044601⋅ⅈ⎤
⎢1  0  0  0  ─────────── + ────────────⎥
⎢            11140729060    5570364530 ⎥
⎢                                      ⎥
⎢               27250512   94696648⋅ⅈ  ⎥
⎢0  1  0  0    ───────── + ──────────  ⎥
⎢              557036453   557036453   ⎥
⎢                                      ⎥
⎢            1613687801   2920269318⋅ⅈ ⎥
⎢0  0  1  0  ────────── + ──────────── ⎥
⎢            2785182265    2785182265  ⎥
⎢                                      ⎥
⎢              1038803244   955211128⋅ⅈ⎥
⎢0  0  0  1  - ────────── + ───────────⎥
⎢              2785182265    2785182265⎥
⎢                                      ⎥
⎣0  0  0  0              0             ⎦
```
Without expand the output is enormous which explains why it is slow:
```julia
In [29]: t                                                                                                                                                                                                         
Out[29]: 
⎡                               ⎛  231   129⋅ⅈ⎞ ⎛  103   53⋅ⅈ⎞         ⎛12147279   6885633⋅ⅈ⎞ ⎛⎛12147279   6885633⋅ⅈ⎞ ⎛⎛  103   53⋅ⅈ⎞ ⎛693   387⋅ⅈ   ⎛  19   5⋅ⅈ⎞ ⎛63   ⎛  149   49⋅ⅈ⎞           3⋅ⅈ⎞⎞   ⎛  ⎛  19
⎢            144115188075855872⋅⎜- ─── - ─────⎟⋅⎜- ─── - ────⎟⋅(1 - ⅈ)⋅⎜──────── - ─────────⎟⋅⎜⎜──────── + ─────────⎟⋅⎜⎜- ─── + ────⎟⋅⎜─── - ───── - ⎜- ── + ───⎟⋅⎜── + ⎜- ─── + ────⎟⋅(1 + ⅈ) + ───⎟⎟ - ⎜- ⎜- ──
⎢                               ⎝   64     64 ⎠ ⎝   32    16 ⎠         ⎝ 524288      524288 ⎠ ⎝⎝ 524288      524288 ⎠ ⎝⎝   32    16 ⎠ ⎝256    256    ⎝  4     4 ⎠ ⎝32   ⎝   64    32 ⎠            4 ⎠⎠   ⎝  ⎝  4 
⎢1  0  0  0  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
⎢                                                                                                                                                                                                                
⎢                                                                                                                                                                                                                
⎢                                                                                                                   ⎛  231   129⋅ⅈ⎞ ⎛  103   53⋅ⅈ⎞ ⎛12147279   6885633⋅ⅈ⎞ ⎛  ⎛⎛  103   53⋅ⅈ⎞ ⎛  ⎛⎛  825   147⋅ⅈ⎞ 
⎢                                                                                                288230376151711744⋅⎜- ─── - ─────⎟⋅⎜- ─── - ────⎟⋅⎜──────── - ─────────⎟⋅⎜- ⎜⎜- ─── + ────⎟⋅⎜- ⎜⎜- ─── - ─────⎟⋅
⎢                                                                                                                   ⎝   64     64 ⎠ ⎝   32    16 ⎠ ⎝ 524288      524288 ⎠ ⎝  ⎝⎝   32    16 ⎠ ⎝  ⎝⎝   64     32 ⎠ 
⎢0  1  0  0                                                                                      ────────────────────────────────────────────────────────────────────────────────────────────────────────────────
⎢                                                                                                                                                                                                                
⎢                                                                                                                                                                                                                
⎢                                                                                                                                                                                                                
⎢                                                                                                                                                                                                                
⎢                                                                                                                                                                                                                
⎢0  0  1  0                                                                                                                                                                                                      
⎢                                                                                                                                                                                                                
⎢                                                                                                                                                                                                                
⎢                                                                                                                                                                                                                
⎢                                                                                                                                                                                                                
⎢                                                                                                                                                                                                                
⎢0  0  0  1                                                                                                                                                                                                      
⎢                                                                                                                                                                                                                
⎢                                                                                                                                                                                                                
⎣0  0  0  0                                                                                                                                                                                                      

   5⋅ⅈ⎞ ⎛⎛  5   39⋅ⅈ⎞                               ⎞   ⎛  231   129⋅ⅈ⎞          ⎞ ⎛  ⎛  19           ⎛17   13⋅ⅈ⎞   5⋅ⅈ⎞ ⎛63   ⎛  149   49⋅ⅈ⎞           3⋅ⅈ⎞   ⎛  231   129⋅ⅈ⎞                           ⎞⎞   ⎛⎛ 
 + ───⎟⋅⎜⎜- ─ - ────⎟⋅(1 + ⅈ) - (1/2 - ⅈ)⋅(21/8 + ⅈ)⎟ + ⎜- ─── + ─────⎟⋅(1/2 - ⅈ)⎟⋅⎜- ⎜- ── + (1 + ⅈ)⋅⎜── - ────⎟ + ───⎟⋅⎜── + ⎜- ─── + ────⎟⋅(1 + ⅈ) + ───⎟ + ⎜- ─── + ─────⎟⋅(-3/2 + (1/2 - ⅈ)⋅(1 + ⅈ))⎟⎟ - ⎜⎜-
    4 ⎠ ⎝⎝  8    16 ⎠                               ⎠   ⎝   64     64 ⎠          ⎠ ⎝  ⎝  2            ⎝4     2  ⎠    2 ⎠ ⎝32   ⎝   64    32 ⎠            4 ⎠   ⎝   64     64 ⎠                           ⎠⎠   ⎝⎝ 
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 
          ⎛  19   5⋅ⅈ⎞ ⎛1   13⋅ⅈ⎞⎞ ⎛63   ⎛  149   49⋅ⅈ⎞           3⋅ⅈ⎞   ⎛  231   129⋅ⅈ⎞ ⎛3    ⎛  5   39⋅ⅈ⎞           39⋅ⅈ⎞⎞   ⎛⎛  231   129⋅ⅈ⎞ ⎛  ⎛1   13⋅ⅈ⎞                               ⎞   ⎛⎛  825   147⋅ⅈ⎞ 
(1 + ⅈ) - ⎜- ── + ───⎟⋅⎜─ + ────⎟⎟⋅⎜── + ⎜- ─── + ────⎟⋅(1 + ⅈ) + ───⎟ + ⎜- ─── + ─────⎟⋅⎜── + ⎜- ─ - ────⎟⋅(1 + ⅈ) + ────⎟⎟ - ⎜⎜- ─── + ─────⎟⋅⎜- ⎜─ + ────⎟⋅(1/2 - ⅈ) + (1 + ⅈ)⋅(21/8 + ⅈ)⎟ - ⎜⎜- ─── - ─────⎟⋅
          ⎝  4     4 ⎠ ⎝4    4  ⎠⎠ ⎝32   ⎝   64    32 ⎠            4 ⎠   ⎝   64     64 ⎠ ⎝16   ⎝  8    16 ⎠            16 ⎠⎠   ⎝⎝   64     64 ⎠ ⎝  ⎝4    4  ⎠                               ⎠   ⎝⎝   64     32 ⎠ 
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 
                       ⎛  103   53⋅ⅈ⎞ ⎛12147279   6885633⋅ⅈ⎞ ⎛  ⎛⎛  231   129⋅ⅈ⎞ ⎛9   ⎛  19   5⋅ⅈ⎞           55⋅ⅈ⎞   ⎛  ⎛9   55⋅ⅈ⎞                      ⎛2473   137⋅ⅈ⎞⎞ ⎛  19           ⎛17   13⋅ⅈ⎞   5⋅ⅈ⎞⎞ ⎛⎛  1
       140737488355328⋅⎜- ─── - ────⎟⋅⎜──────── - ─────────⎟⋅⎜- ⎜⎜- ─── + ─────⎟⋅⎜─ + ⎜- ── + ───⎟⋅(1 + ⅈ) + ────⎟ - ⎜- ⎜─ + ────⎟⋅(21/8 + ⅈ) + (1 + ⅈ)⋅⎜──── + ─────⎟⎟⋅⎜- ── + (1 + ⅈ)⋅⎜── - ────⎟ + ───⎟⎟⋅⎜⎜- ─
                       ⎝   32    16 ⎠ ⎝ 524288      524288 ⎠ ⎝  ⎝⎝   64     64 ⎠ ⎝2   ⎝  4     4 ⎠            8  ⎠   ⎝  ⎝4    16 ⎠                      ⎝256      64 ⎠⎠ ⎝  2            ⎝4     2  ⎠    2 ⎠⎠ ⎝⎝   
       ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 
                                                                                                                                                                              ⎛12147279   6885633⋅ⅈ⎞ ⎛⎛  103   53
                                                                                                                                                                 137438953472⋅⎜──────── - ─────────⎟⋅⎜⎜- ─── + ──
                                                                                                                                                                              ⎝ 524288      524288 ⎠ ⎝⎝   32    1
                                                                                                                                                                 ────────────────────────────────────────────────
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 

 103   53⋅ⅈ⎞ ⎛  ⎛⎛  825   147⋅ⅈ⎞           ⎛  19   5⋅ⅈ⎞ ⎛1   13⋅ⅈ⎞⎞ ⎛63   ⎛  149   49⋅ⅈ⎞           3⋅ⅈ⎞   ⎛  231   129⋅ⅈ⎞ ⎛3    ⎛  5   39⋅ⅈ⎞           39⋅ⅈ⎞⎞   ⎛⎛  231   129⋅ⅈ⎞ ⎛  ⎛1   13⋅ⅈ⎞                   
 ─── + ────⎟⋅⎜- ⎜⎜- ─── - ─────⎟⋅(1 + ⅈ) - ⎜- ── + ───⎟⋅⎜─ + ────⎟⎟⋅⎜── + ⎜- ─── + ────⎟⋅(1 + ⅈ) + ───⎟ + ⎜- ─── + ─────⎟⋅⎜── + ⎜- ─ - ────⎟⋅(1 + ⅈ) + ────⎟⎟ - ⎜⎜- ─── + ─────⎟⋅⎜- ⎜─ + ────⎟⋅(1/2 - ⅈ) + (1 + ⅈ
  32    16 ⎠ ⎝  ⎝⎝   64     32 ⎠           ⎝  4     4 ⎠ ⎝4    4  ⎠⎠ ⎝32   ⎝   64    32 ⎠            4 ⎠   ⎝   64     64 ⎠ ⎝16   ⎝  8    16 ⎠            16 ⎠⎠   ⎝⎝   64     64 ⎠ ⎝  ⎝4    4  ⎠                   
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                      74536084581485956328925    
                                                                                                                                                                                                                 
          ⎛  19   5⋅ⅈ⎞ ⎛1   13⋅ⅈ⎞⎞ ⎛⎛  5   39⋅ⅈ⎞                               ⎞⎞ ⎛  ⎛  19           ⎛17   13⋅ⅈ⎞   5⋅ⅈ⎞ ⎛63   ⎛  149   49⋅ⅈ⎞           3⋅ⅈ⎞   ⎛  231   129⋅ⅈ⎞                           ⎞⎞ ⎛  ⎛⎛ 
(1 + ⅈ) - ⎜- ── + ───⎟⋅⎜─ + ────⎟⎟⋅⎜⎜- ─ - ────⎟⋅(1 + ⅈ) - (1/2 - ⅈ)⋅(21/8 + ⅈ)⎟⎟⋅⎜- ⎜- ── + (1 + ⅈ)⋅⎜── - ────⎟ + ───⎟⋅⎜── + ⎜- ─── + ────⎟⋅(1 + ⅈ) + ───⎟ + ⎜- ─── + ─────⎟⋅(-3/2 + (1/2 - ⅈ)⋅(1 + ⅈ))⎟⎟⋅⎜- ⎜⎜-
          ⎝  4     4 ⎠ ⎝4    4  ⎠⎠ ⎝⎝  8    16 ⎠                               ⎠⎠ ⎝  ⎝  2            ⎝4     2  ⎠    2 ⎠ ⎝32   ⎝   64    32 ⎠            4 ⎠   ⎝   64     64 ⎠                           ⎠⎠ ⎝  ⎝⎝ 
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                     74536084581485956328925     
                                                                                                                                                                                                                 
03   53⋅ⅈ⎞ ⎛  ⎛⎛  825   147⋅ⅈ⎞           ⎛  19   5⋅ⅈ⎞ ⎛1   13⋅ⅈ⎞⎞ ⎛63   ⎛  149   49⋅ⅈ⎞           3⋅ⅈ⎞   ⎛  231   129⋅ⅈ⎞ ⎛3    ⎛  5   39⋅ⅈ⎞           39⋅ⅈ⎞⎞   ⎛⎛  231   129⋅ⅈ⎞ ⎛  ⎛1   13⋅ⅈ⎞                     
── + ────⎟⋅⎜- ⎜⎜- ─── - ─────⎟⋅(1 + ⅈ) - ⎜- ── + ───⎟⋅⎜─ + ────⎟⎟⋅⎜── + ⎜- ─── + ────⎟⋅(1 + ⅈ) + ───⎟ + ⎜- ─── + ─────⎟⋅⎜── + ⎜- ─ - ────⎟⋅(1 + ⅈ) + ────⎟⎟ - ⎜⎜- ─── + ─────⎟⋅⎜- ⎜─ + ────⎟⋅(1/2 - ⅈ) + (1 + ⅈ)⋅
32    16 ⎠ ⎝  ⎝⎝   64     32 ⎠           ⎝  4     4 ⎠ ⎝4    4  ⎠⎠ ⎝32   ⎝   64    32 ⎠            4 ⎠   ⎝   64     64 ⎠ ⎝16   ⎝  8    16 ⎠            16 ⎠⎠   ⎝⎝   64     64 ⎠ ⎝  ⎝4    4  ⎠                     
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                       2129541572568953925       
                                                                                                                                                                                                                 
⋅ⅈ⎞ ⎛  ⎛⎛  825   147⋅ⅈ⎞           ⎛  19   5⋅ⅈ⎞ ⎛1   13⋅ⅈ⎞⎞ ⎛63   ⎛  149   49⋅ⅈ⎞           3⋅ⅈ⎞   ⎛  231   129⋅ⅈ⎞ ⎛3    ⎛  5   39⋅ⅈ⎞           39⋅ⅈ⎞⎞   ⎛⎛  231   129⋅ⅈ⎞ ⎛  ⎛1   13⋅ⅈ⎞                            
──⎟⋅⎜- ⎜⎜- ─── - ─────⎟⋅(1 + ⅈ) - ⎜- ── + ───⎟⋅⎜─ + ────⎟⎟⋅⎜── + ⎜- ─── + ────⎟⋅(1 + ⅈ) + ───⎟ + ⎜- ─── + ─────⎟⋅⎜── + ⎜- ─ - ────⎟⋅(1 + ⅈ) + ────⎟⎟ - ⎜⎜- ─── + ─────⎟⋅⎜- ⎜─ + ────⎟⋅(1/2 - ⅈ) + (1 + ⅈ)⋅(21/8 +
6 ⎠ ⎝  ⎝⎝   64     32 ⎠           ⎝  4     4 ⎠ ⎝4    4  ⎠⎠ ⎝32   ⎝   64    32 ⎠            4 ⎠   ⎝   64     64 ⎠ ⎝16   ⎝  8    16 ⎠            16 ⎠⎠   ⎝⎝   64     64 ⎠ ⎝  ⎝4    4  ⎠                            
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                           97484164457265        
                                                                                                                                                                                                                 
                                                                                                                                                                                                 0               

            ⎞   ⎛⎛  825   147⋅ⅈ⎞           ⎛  19   5⋅ⅈ⎞ ⎛1   13⋅ⅈ⎞⎞ ⎛⎛  5   39⋅ⅈ⎞                               ⎞⎞ ⎛  ⎛  19           ⎛17   13⋅ⅈ⎞   5⋅ⅈ⎞ ⎛63   ⎛  149   49⋅ⅈ⎞           3⋅ⅈ⎞   ⎛  231   129⋅ⅈ⎞   
)⋅(21/8 + ⅈ)⎟ - ⎜⎜- ─── - ─────⎟⋅(1 + ⅈ) - ⎜- ── + ───⎟⋅⎜─ + ────⎟⎟⋅⎜⎜- ─ - ────⎟⋅(1 + ⅈ) - (1/2 - ⅈ)⋅(21/8 + ⅈ)⎟⎟⋅⎜- ⎜- ── + (1 + ⅈ)⋅⎜── - ────⎟ + ───⎟⋅⎜── + ⎜- ─── + ────⎟⋅(1 + ⅈ) + ───⎟ + ⎜- ─── + ─────⎟⋅(-
            ⎠   ⎝⎝   64     32 ⎠           ⎝  4     4 ⎠ ⎝4    4  ⎠⎠ ⎝⎝  8    16 ⎠                               ⎠⎠ ⎝  ⎝  2            ⎝4     2  ⎠    2 ⎠ ⎝32   ⎝   64    32 ⎠            4 ⎠   ⎝   64     64 ⎠   
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 
 231   129⋅ⅈ⎞ ⎛9   ⎛  19   5⋅ⅈ⎞           55⋅ⅈ⎞   ⎛  ⎛9   55⋅ⅈ⎞                      ⎛2473   137⋅ⅈ⎞⎞ ⎛  19           ⎛17   13⋅ⅈ⎞   5⋅ⅈ⎞⎞ ⎛⎛  5   39⋅ⅈ⎞                               ⎞   ⎛  103   53⋅ⅈ⎞ ⎛  ⎛9   5
 ─── + ─────⎟⋅⎜─ + ⎜- ── + ───⎟⋅(1 + ⅈ) + ────⎟ - ⎜- ⎜─ + ────⎟⋅(21/8 + ⅈ) + (1 + ⅈ)⋅⎜──── + ─────⎟⎟⋅⎜- ── + (1 + ⅈ)⋅⎜── - ────⎟ + ───⎟⎟⋅⎜⎜- ─ - ────⎟⋅(1 + ⅈ) - (1/2 - ⅈ)⋅(21/8 + ⅈ)⎟ + ⎜- ─── + ────⎟⋅⎜- ⎜─ + ─
  64     64 ⎠ ⎝2   ⎝  4     4 ⎠            8  ⎠   ⎝  ⎝4    16 ⎠                      ⎝256      64 ⎠⎠ ⎝  2            ⎝4     2  ⎠    2 ⎠⎠ ⎝⎝  8    16 ⎠                               ⎠   ⎝   32    16 ⎠ ⎝  ⎝4    
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 
          ⎞   ⎛⎛  825   147⋅ⅈ⎞           ⎛  19   5⋅ⅈ⎞ ⎛1   13⋅ⅈ⎞⎞ ⎛⎛  5   39⋅ⅈ⎞                               ⎞⎞ ⎛  ⎛  19           ⎛17   13⋅ⅈ⎞   5⋅ⅈ⎞ ⎛63   ⎛  149   49⋅ⅈ⎞           3⋅ⅈ⎞   ⎛  231   129⋅ⅈ⎞     
(21/8 + ⅈ)⎟ - ⎜⎜- ─── - ─────⎟⋅(1 + ⅈ) - ⎜- ── + ───⎟⋅⎜─ + ────⎟⎟⋅⎜⎜- ─ - ────⎟⋅(1 + ⅈ) - (1/2 - ⅈ)⋅(21/8 + ⅈ)⎟⎟⋅⎜- ⎜- ── + (1 + ⅈ)⋅⎜── - ────⎟ + ───⎟⋅⎜── + ⎜- ─── + ────⎟⋅(1 + ⅈ) + ───⎟ + ⎜- ─── + ─────⎟⋅(-3/
          ⎠   ⎝⎝   64     32 ⎠           ⎝  4     4 ⎠ ⎝4    4  ⎠⎠ ⎝⎝  8    16 ⎠                               ⎠⎠ ⎝  ⎝  2            ⎝4     2  ⎠    2 ⎠ ⎝32   ⎝   64    32 ⎠            4 ⎠   ⎝   64     64 ⎠     
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 
   ⎞   ⎛⎛  825   147⋅ⅈ⎞           ⎛  19   5⋅ⅈ⎞ ⎛1   13⋅ⅈ⎞⎞ ⎛⎛  5   39⋅ⅈ⎞                               ⎞⎞ ⎛  ⎛  19           ⎛17   13⋅ⅈ⎞   5⋅ⅈ⎞ ⎛63   ⎛  149   49⋅ⅈ⎞           3⋅ⅈ⎞   ⎛  231   129⋅ⅈ⎞            
 ⅈ)⎟ - ⎜⎜- ─── - ─────⎟⋅(1 + ⅈ) - ⎜- ── + ───⎟⋅⎜─ + ────⎟⎟⋅⎜⎜- ─ - ────⎟⋅(1 + ⅈ) - (1/2 - ⅈ)⋅(21/8 + ⅈ)⎟⎟⋅⎜- ⎜- ── + (1 + ⅈ)⋅⎜── - ────⎟ + ───⎟⋅⎜── + ⎜- ─── + ────⎟⋅(1 + ⅈ) + ───⎟ + ⎜- ─── + ─────⎟⋅(-3/2 + (1/
   ⎠   ⎝⎝   64     32 ⎠           ⎝  4     4 ⎠ ⎝4    4  ⎠⎠ ⎝⎝  8    16 ⎠                               ⎠⎠ ⎝  ⎝  2            ⎝4     2  ⎠    2 ⎠ ⎝32   ⎝   64    32 ⎠            4 ⎠   ⎝   64     64 ⎠            
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 

                        ⎞⎞ ⎛  ⎛  ⎛  19   5⋅ⅈ⎞ ⎛⎛  5   39⋅ⅈ⎞                               ⎞   ⎛  231   129⋅ⅈ⎞          ⎞ ⎛⎛  231   129⋅ⅈ⎞ ⎛9   ⎛  19   5⋅ⅈ⎞           55⋅ⅈ⎞   ⎛  ⎛9   55⋅ⅈ⎞                      
3/2 + (1/2 - ⅈ)⋅(1 + ⅈ))⎟⎟⋅⎜- ⎜- ⎜- ── + ───⎟⋅⎜⎜- ─ - ────⎟⋅(1 + ⅈ) - (1/2 - ⅈ)⋅(21/8 + ⅈ)⎟ + ⎜- ─── + ─────⎟⋅(1/2 - ⅈ)⎟⋅⎜⎜- ─── + ─────⎟⋅⎜─ + ⎜- ── + ───⎟⋅(1 + ⅈ) + ────⎟ - ⎜- ⎜─ + ────⎟⋅(21/8 + ⅈ) + (1 + ⅈ)⋅
                        ⎠⎠ ⎝  ⎝  ⎝  4     4 ⎠ ⎝⎝  8    16 ⎠                               ⎠   ⎝   64     64 ⎠          ⎠ ⎝⎝   64     64 ⎠ ⎝2   ⎝  4     4 ⎠            8  ⎠   ⎝  ⎝4    16 ⎠                      
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 
5⋅ⅈ⎞                      ⎛2473   137⋅ⅈ⎞⎞⎞   ⎛12147279   6885633⋅ⅈ⎞ ⎛⎛  103   53⋅ⅈ⎞ ⎛63   ⎛  149   49⋅ⅈ⎞           3⋅ⅈ⎞   ⎛⎛  5   39⋅ⅈ⎞                               ⎞ ⎛  ⎛  19           ⎛17   13⋅ⅈ⎞   5⋅ⅈ⎞ ⎛63
───⎟⋅(21/8 + ⅈ) + (1 + ⅈ)⋅⎜──── + ─────⎟⎟⎟ + ⎜──────── + ─────────⎟⋅⎜⎜- ─── + ────⎟⋅⎜── + ⎜- ─── + ────⎟⋅(1 + ⅈ) + ───⎟ - ⎜⎜- ─ - ────⎟⋅(1 + ⅈ) - (1/2 - ⅈ)⋅(21/8 + ⅈ)⎟⋅⎜- ⎜- ── + (1 + ⅈ)⋅⎜── - ────⎟ + ───⎟⋅⎜──
16 ⎠                      ⎝256      64 ⎠⎠⎠   ⎝ 524288      524288 ⎠ ⎝⎝   32    16 ⎠ ⎝32   ⎝   64    32 ⎠            4 ⎠   ⎝⎝  8    16 ⎠                               ⎠ ⎝  ⎝  2            ⎝4     2  ⎠    2 ⎠ ⎝32
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 
                      ⎞⎞   ⎛12147279   6885633⋅ⅈ⎞ ⎛  ⎛  19           ⎛17   13⋅ⅈ⎞   5⋅ⅈ⎞ ⎛63   ⎛  149   49⋅ⅈ⎞           3⋅ⅈ⎞   ⎛  231   129⋅ⅈ⎞                           ⎞⎞                                       
2 + (1/2 - ⅈ)⋅(1 + ⅈ))⎟⎟ + ⎜──────── + ─────────⎟⋅⎜- ⎜- ── + (1 + ⅈ)⋅⎜── - ────⎟ + ───⎟⋅⎜── + ⎜- ─── + ────⎟⋅(1 + ⅈ) + ───⎟ + ⎜- ─── + ─────⎟⋅(-3/2 + (1/2 - ⅈ)⋅(1 + ⅈ))⎟⎟                                       
                      ⎠⎠   ⎝ 524288      524288 ⎠ ⎝  ⎝  2            ⎝4     2  ⎠    2 ⎠ ⎝32   ⎝   64    32 ⎠            4 ⎠   ⎝   64     64 ⎠                           ⎠⎠                                       
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────                                       
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 
               ⎞⎞                                                                                                                                                                                                
2 - ⅈ)⋅(1 + ⅈ))⎟⎟                                                                                                                                                                                                
               ⎠⎠                                                                                                                                                                                                
─────────────────                                                                                                                                                                                                
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 
                                                                                                                                                                                                                 

⎛2473   137⋅ⅈ⎞⎞ ⎛  19           ⎛17   13⋅ⅈ⎞   5⋅ⅈ⎞⎞   ⎛  103   53⋅ⅈ⎞ ⎛⎛  231   129⋅ⅈ⎞ ⎛9   55⋅ⅈ⎞   ⎛  19   5⋅ⅈ⎞ ⎛  ⎛9   55⋅ⅈ⎞                      ⎛2473   137⋅ⅈ⎞⎞⎞⎞⎞⎤
⎜──── + ─────⎟⎟⋅⎜- ── + (1 + ⅈ)⋅⎜── - ────⎟ + ───⎟⎟ + ⎜- ─── + ────⎟⋅⎜⎜- ─── + ─────⎟⋅⎜─ + ────⎟ - ⎜- ── + ───⎟⋅⎜- ⎜─ + ────⎟⋅(21/8 + ⅈ) + (1 + ⅈ)⋅⎜──── + ─────⎟⎟⎟⎟⎟⎥
⎝256      64 ⎠⎠ ⎝  2            ⎝4     2  ⎠    2 ⎠⎠   ⎝   32    16 ⎠ ⎝⎝   64     64 ⎠ ⎝4    16 ⎠   ⎝  4     4 ⎠ ⎝  ⎝4    16 ⎠                      ⎝256      64 ⎠⎠⎠⎠⎠⎥
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
   ⎛  149   49⋅ⅈ⎞           3⋅ⅈ⎞   ⎛  231   129⋅ⅈ⎞                           ⎞⎞⎞                                                                                     ⎥
 + ⎜- ─── + ────⎟⋅(1 + ⅈ) + ───⎟ + ⎜- ─── + ─────⎟⋅(-3/2 + (1/2 - ⅈ)⋅(1 + ⅈ))⎟⎟⎟                                                                                     ⎥
   ⎝   64    32 ⎠            4 ⎠   ⎝   64     64 ⎠                           ⎠⎠⎠                                                                                     ⎥
────────────────────────────────────────────────────────────────────────────────                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎥
                                                                                                                                                                     ⎦


```

**Comment by adukova** [comment]
@oscarbenjamin
Since intermediate calculations lead to large numbers, we must use gmpy2 for job with large expressions.  However, if we set class of matrix entries as GMPY mpq class,  the functions matrix, rank,  rref and etc.  will  use class rational and gmpy2 doesn't work.   Why?

**Comment by oscarbenjamin** [comment]
We probably just need to call expand in the right place. Maybe here:
https://github.com/sympy/sympy/blob/97f3bd52ffb960b2fe52c9fe88d0b543906e27c4/sympy/matrices/matrices.py#L695-L699

**Comment by adukova** [comment]
@oscarbenjamin 
Sorry, I don't understand since I am beginner in Python. Do you suggest to create my own function rref in order to I can use the class mpq?

**Comment by adukova** [comment]
@oscarbenjamin 
I would like to note that maple does this task instantly.

**Comment by oscarbenjamin** [comment]
I was suggesting that this could possibly be fixed in SymPy by adding a call to expand there. I tried the following diff from master:
```diff
$ git diff
diff --git a/sympy/matrices/matrices.py b/sympy/matrices/matrices.py
index 3096ca9a53..e2ad6add27 100644
--- a/sympy/matrices/matrices.py
+++ b/sympy/matrices/matrices.py
@@ -696,7 +696,7 @@ def cross_cancel(a, i, b, j):
             """Does the row op row[i] = a*row[i] - b*row[j]"""
             q = (j - i)*cols
             for p in range(i*cols, (i + 1)*cols):
-                mat[p] = a*mat[p] - b*mat[p + q]
+                mat[p] = (a*mat[p] - b*mat[p + q]).expand()
 
         piv_row, piv_col = 0, 0
         pivot_cols = []

```
And now I get:
```
In [2]: %time T.rank()                                                                                                            
CPU times: user 1.3 s, sys: 9.22 ms, total: 1.31 s
Wall time: 1.32 s
Out[2]: 8
```

So it gives the correct answer in 1.3 seconds.

Possibly that would break some other things though...

**Comment by adukova** [comment]
@oscarbenjamin
Thank you very much for your help!
I will test your version matrices.py on other matrices.

**Comment by oscarbenjamin** [comment]
That change gives one test failure in matrices:
```julia
In [1]: A = Matrix([ 
   ...:             [1, 1, 1, 0], 
   ...:             [-2, -1, 0, -1], 
   ...:             [0, 0, -1, -1], 
   ...:             [0, 0, 2, 1]])                                                                                                

In [2]: (P, J) = A.jordan_form()                                                                                                  

In [3]: simplify(P)                                                                                                               
Out[3]: 
⎡           -ⅈ                   ⅈ    ⎤
⎢  -ⅈ       ───        ⅈ         ─    ⎥
⎢            2                   2    ⎥
⎢                                     ⎥
⎢-1 + ⅈ      0       -1 - ⅈ      0    ⎥
⎢                                     ⎥
⎢        ⅈ⋅(-1 + ⅈ)          ⅈ⋅(1 + ⅈ)⎥
⎢  0     ──────────    0     ─────────⎥
⎢            2                   2    ⎥
⎢                                     ⎥
⎣  0         1         0         1    ⎦
```

Under the PR it is
```julia
In [4]: simplify(P)                                                                                                               
Out[4]: 
⎡           -ⅈ                  ⅈ   ⎤
⎢  -ⅈ       ───        ⅈ        ─   ⎥
⎢            2                  2   ⎥
⎢                                   ⎥
⎢-1 + ⅈ      0       -1 - ⅈ     0   ⎥
⎢                                   ⎥
⎢        ⅈ⋅(-1 + ⅈ)            1   ⅈ⎥
⎢  0     ──────────    0     - ─ + ─⎥
⎢            2                 2   2⎥
⎢                                   ⎥
⎣  0         1         0        1   ⎦
```
The difference is in row 3, col 4 but the expressions are equivalent so I think that's fine and the test can just be updated.

Speed-wise running the not slow matrices tests takes 45 seconds with this change compare to 49 seconds on master. That looks like the change maybe speeds up some other things.

This would make a good pull request if you are interested in contributing. Do you want to send a PR? Otherwise I can label this as easy to fix so that someone else can write a PR.

**Comment by adukova** [comment]
@oscarbenjamin
Sorry, I don’t know what is PR. Maybe it is programme revision. 

Since I am beginner, I am afraid to change something. 

We have run our programme with your change and for the example with wrong result we have obtained the right result. 

Thank you very much for your advice! 

However, the problem of large numbers still exists. We have a lot of examples where calculations are very slowly. From matrices.py we use only rank and null space.

**Comment by oscarbenjamin** [comment]
It looks like the particular issue you mentioned here can be fixed easily. With further testing I found that the fix needs to be
```diff
diff --git a/sympy/matrices/matrices.py b/sympy/matrices/matrices.py
index 3096ca9a53..c54bcdd6f3 100644
--- a/sympy/matrices/matrices.py
+++ b/sympy/matrices/matrices.py
@@ -696,7 +696,14 @@ def cross_cancel(a, i, b, j):
             """Does the row op row[i] = a*row[i] - b*row[j]"""
             q = (j - i)*cols
             for p in range(i*cols, (i + 1)*cols):
-                mat[p] = a*mat[p] - b*mat[p + q]
+                matp = a*mat[p] - b*mat[p + q]
+                try:
+                    e = matp.expand
+                except AttributeError:
+                    pass
+                else:
+                    matp = e()
+                mat[p] = matp
 
         piv_row, piv_col = 0, 0
         pivot_cols = []
```
because many objects in matrices don't have an expand method.

I will mark this as easy to fix so that someone else can send a PR (pull request).

It's good to keep separate problems in separate issues so if you have other problems still then please open a new issue describing them.

**Comment by adukova** [comment]
@oscarbenjamin
Thank you very much for your invaluable help!
 The problem with the speed even for real matrices still exists.

I think that I will open a new issue about this. 

P.S. Thank you for adding the labels to my issue.

**Comment by smichr** [comment]
> but the expressions are equivalent

`m.applyfunc(factor_terms)` before returning would take care of such differences

**Comment by smichr** [comment]
Rather than use a blanket expand, you might try `.xreplace(Transform(
lambda x: expand_mul(x),
lambda x: x.is_Add and sum([int(i.is_Add) for i in x.args])))`

**Comment by oscarbenjamin** [comment]
Or maybe just use
```
if isinstance(matp, Expr):
    matp = expand_mul(matp)
```

**Comment by sylee957** [comment]
There had been similar discussion before, like #10120,
For expanding the terms, I anticipate that it can only guarantee that it works on some subset of expressions like `a + b*I` where both `a` and `b` are numeric integers or such.

`simplify` is used a lot like a magic cure for symbolic math, but if it is a waste of computation, I would consider some algorithm like

Check the type of every matrix elements
-> If the matrix contains purely complex integers
-> Apply gaussian elimination with a specific simplification strategy.

**Comment by adukova** [comment]
@oscarbenjamin
Dear Oskar,

Thank you very much for your advice to my daughter Adukova Nataliya (GitHub issue # 16823).
Your advice help to improve the work of my SymPy module for the Wiener-Hopf factorization 
of matrix polynomials. 

Can I thank you in my article for Journal of Symbolic Computation?
Unfortunately, I only know you as Oscar Benjamin in the forum GitHub.
Can I give that name in "Acknowledgments"?

Best wishes,

V. Adukov

**Comment by oscarbenjamin** [comment]
@adukova No problem. Yes you can put that in the acknowledgments.

**Comment by adukova** [comment]
@oscarbenjamin
Thank you

**Comment by Pristine-Cat** [comment]
> We probably just need to call expand in the right place. Maybe here:
> https://github.com/sympy/sympy/blob/97f3bd52ffb960b2fe52c9fe88d0b543906e27c4/sympy/matrices/matrices.py#L695-L699

I had a quick look at it and I don't think that will do it, not for matrix multiplication. I think the place for the fix is at the end of complex operations which can generate convoluted matrices like pow or inv or even mul, or operations which take the matrix to a different basis and bring it back afterwards - the simplification step should come after those. I am thinking adding a flag to be recursed to avoid the simplification until all the calculations are done. Also should a full `simplify()` be considered or is it too slow?

**Comment by oscarbenjamin** [comment]
Full simplify can be arbitrarily slow. I think (hope?) we should be able to identify the right kind of simplification here since we know what kind of expressions we are creating

**Comment by Pristine-Cat** [comment]
But we don't know what the matrix contains, arbitrary objects, expressions, etc... which could alter the outcome of the simplification. Or do you mean limit the simplification to the structure of the operation itself? Which could miss a large class of possible reductions?

**Comment by oscarbenjamin** [comment]
I think we want simplifications that can prevent expression blowup. The blowup itself is caused by the basic algorithms in the matrix operations, usually adding and multiplying. So probably a critical question would be how to reduce (where possible) expressions of the form `a*x+b*y` where any variable might be of the same form and the operation might happen repeatedly. There are a bunch of relevant functions: collect, cancel, factor, expand etc that are all designed to work with combinations of Adds and Muls but what is needed is for someone to work through some use cases to see which functions is best and where in the chain to apply it.

**Comment by Pristine-Cat** [comment]
I was looking at `cancel` and `expand`. `collect` could also help but would involve finding the best variable to collect. `factor` scares me a little because I've implemented polynomial factoring before and know that it involves raising the poly to a power of a power and this can get out of hand in degenerate cases, it may even be a significant contributor to the arbitrary performance of normal simplify.

The other question I had was whether to defer the simplification till the end of all operations requested by the user or do them always at the end of critical operations which can blow up the matrix and I think the latter is far better to prevent intermediate products slowing everything down.

What I am thinking is implement a 'simplify light' function for matrices and call it at the end of only certain operations, what I would like to know is apart from `__pow__()` and `inv()`, which other operations tend to blow up?

**Comment by oscarbenjamin** [comment]
> which other operations tend to blow up?

I think a big one is `__mul__`. We get blowup in `__pow__` just because the recursive path uses `__mul__`. The issue we are talking on is about `rref`. It's possible that results based on the Jordan form are overly complicated because of rref so improving rref might improve exp, log, `__pow__` etc.

I agree that preventing blowup means that simplification shouldn't wait until the end. If things blowup too much we never get to the end or the result becomes to complicated to simplify by then. Also yes a special purpose simplification routine is probably useful

**Comment by oscarbenjamin** [comment]
This is now fixed and gives the correct result in 2 seconds:
```
In [3]: %time T.rank()                                                                                                                                        
CPU times: user 1.92 s, sys: 17.5 ms, total: 1.94 s
Wall time: 1.95 s
Out[3]: 8
```
The fix came from #18563.

This issue can be closed if a test is added for computing the rank of the matrix T above

**Comment by Pristine-Cat** [comment]
> This is now fixed and gives the correct result in 2 seconds:

Yes, but only by avoiding the code path which originally took a very long time and computed the incorrect result here. The underlying problem probably remains if rank() returns 9 without the new matrix simplification.

**Comment by oscarbenjamin** [comment]
> The underlying problem probably remains

That's true. I just don't know how we can diagnose it from the report here. My guess is that zero-checking fails on some blown-up expression but I don't know how to pick that out from the example which presumably checks many expressions...

**Comment by vinitwadgaonkar** [comment]
IS This issue resolved if not can i work on it

**Comment by oscarbenjamin** [comment]
The rank issue is fixed because a modified algorithm is being used but the underlying bug from the old algorithm possibly remains.

The issue is to figure out what was causing the bug in the previous rank calculations. I don't think it's very easy to diagnose from the example here so maybe this issue should be closed.

**Comment by oscarbenjamin** [comment]
I'm not sure if the example here has already been added to the tests. If not then it should be. I think then the issue can be closed.

**Comment by Ayush-Malik** [comment]
@oscarbenjamin , I want to add the test case , can you tell me in which file test case should be added and where

**Comment by suryam35** [comment]
@oscarbenjamin this test case has already been added in **sympy/matrices/tests/test_matrices.py**
this issue should be closed.

**Comment by oscarbenjamin** [comment]
We now have new implementations for this. By default dotprodsimp is used which makes this a lot faster:
```python
In [15]: %time T.rank()
CPU times: user 2.96 s, sys: 31.7 ms, total: 2.99 s
Wall time: 3.04 s
Out[15]: 8
```
We also have DomainMatrix which is not yet used in this case but is faster:
```python
In [16]: from sympy.polys.domainmatrix import DomainMatrix

In [17]: dM = DomainMatrix.from_Matrix(T)

In [18]: %time ok = dM.rref()
CPU times: user 205 ms, sys: 798 µs, total: 206 ms
Wall time: 206 ms
```

The problem in the old implementation still indicates a bug somewhere else in sympy though. If we can verify that this gives the correct result then the issue can be closed:
```
from sympy.matrices import dotprodsimp

with dotprodsimp(False):
     print(T.rank())
```
(I think it takes a few hours to run that command)

**Comment by suryam35** [comment]
@oscarbenjamin the command took few hours to execute but gave the correct answer as 8.

**Comment by oscarbenjamin** [comment]
Okay, great. It's likely the problem has been fixed then. It would be nice to bisect to where it got fixed but if it takes a few hours to run then that's going to take days.

I guess we can close this.
