### ISSUE TITLE
Add missing docstring sections in Special submodule

### ISSUE THREAD

**Issue by lglattly** [sympy/sympy#17887]
As part of my Google Season of Docs project with SymPy, I copy edited all of the docstrings in the Special submodule to reflect the new SymPy Docstring Style Guide. While editing, I came across some docstrings that were missing sections or had other issues that need to be addressed. Here is a list of all of the functions in the Special submodule that had an issue and what needs to be fixed:

1. Jn_zeros 
Parameters listed but does not have a parameters section

2. Bspline_basis, bspline_basis_set
In bspline_basis, parameters not pulling into HTML site
Both have parameters listed but do not have a parameters section

3. Interpolating_spline
Parameters listed but does not have a parameters section

4. Fdiff, eval (under DiracDelta)
Parameters listed but do not have a parameters section

5. Fdiff, eval (under Heaviside)
Parameters listed but do not have a parameters section

6. E1(z)
Missing examples section

7. Li (in error functions)
In the Examples section, the example for under the text “Defining the ``li`` function via an integral:” is missing

8. Hyper
Lists properties as part of this class that need to be their own docstrings with their own examples

9. Meijerg
Lists properties as part of this class that need to be their own docstrings with their own examples

10. Appellf1
Missing examples section

11. Jacobi_normalized
Parameters listed but does not have a parameters section

12. Ynm_c
Missing examples section
Parameters listed but does not have a parameters section

13. Znm
Missing examples section

CC @sympy/gsod

**Comment by asmeurer** [comment]
For anyone fixing this be sure to follow the documentation style guide https://docs.sympy.org/dev/documentation-style-guide.html

**Comment by Lokesh2703** [comment]
@asmeurer Can I work on this?

**Comment by Soumi7** [comment]
Hey can you assign me this issue? Also, where can I reach out for questions?

**Comment by smitgajjar** [comment]
Contributors are not assigned with issues here. Anyone can start working and send a relevant PR solving that issue!

**Comment by Soumi7** [comment]
I am facing an error when i run ```make html``` after installing prerequisites. Should I state my problem here or create an issue?

**Comment by asmeurer** [comment]
Just state it here. We can open an new issue if we determine there is a bug in the build process, but most likely there is some issue on your system.

**Comment by Soumi7** [comment]
I am facing this error when I run ```make html``` inside doc:
```
rm -rf _build/logo
mkdir -p _build/logo
python ./generate_logos.py -d
INFO:root: File saved: ./_build/logo/sympy-notail.svg
INFO:root: File saved: ./_build/logo/sympy-notailtext.svg
INFO:root: File saved: ./_build/logo/sympy-notext.svg
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-64px.png -h 64 -w 64
DEBUG:root:return code: 0
ERROR:root:Return code is not 0: Command: convert ./_build/logo/sympy-16px.png ./_build/logo/sympy-32px.png ./_build/logo/sympy-48px.png ./_build/logo/sympy-64px.png ./_build/logo/sympy-favicon.ico
ERROR:root:return code: 1
Makefile:143: recipe for target 'logo' failed
make: *** [logo] Error 1
```

Here are the commands I ran from the start to build:

```git clone git://github.com/sympy/sympy.git
cd sympy
git remote add github git@github.com:Soumi7/sympy.git
conda create -n sympy-dev-py35 python=3.5 mpmath flake8
source activate sympy-dev-py35
flake8 sympy
python setup.py install
git branch branch1
git checkout branch1
sudo apt-get install python-sphinx texlive-latex-recommended dvipng librsvg2-bin imagemagick docbook2x graphviz
sudo apt-get update
python -m pip install sphinx-math-dollar
ls
cd doc
make html
```

**Comment by asmeurer** [comment]
It looks like the generate logos script doesn't print the stdout and stderr when there is an error, so we can't tell what the problem is. This should be fixed. 

What is the output if you run

```
cd doc
convert ./_build/logo/sympy-16px.png ./_build/logo/sympy-32px.png ./_build/logo/sympy-48px.png ./_build/logo/sympy-64px.png ./_build/logo/sympy-favicon.ico
```

**Comment by Soumi7** [comment]
Here is the error i got after running:
```
convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/562.
convert: no images defined `./_build/logo/sympy-favicon.ico' @ error/convert.c/ConvertImageCommand/3282.
```

**Comment by Soumi7** [comment]
I built `imagemagick` from source. However , I am unable to convert the PG delegate to yes after configuring:
```
./configure --with-png=yes 
```

It persistently says that the png delegate isnt there.

**Comment by Soumi7** [comment]
The logo generated but i got this error:

```
Logo generated.
mkdir -p src/.static
mkdir -p _build/html
mkdir -p _build/doctrees
mkdir -p src/modules
PYTHONPATH=..: sphinx-build -b html -d _build/doctrees -W --keep-going src _build/html
Running Sphinx v3.0.3

Extension error:
Could not import extension matplotlib.sphinxext.plot_directive (exception: No module named 'matplotlib')
Makefile:49: recipe for target 'html' failed
make: *** [html] Error 2
```
I installed matplotlib with this command:
```
sudo apt-get install python3-matplotlib
```
However, the **error still shows**. I had matplotlib installed on my system way before as well.

**Comment by asmeurer** [comment]
My guess is that the matplotlib version is too old. The latest version is 3.2.1.

**Comment by asmeurer** [comment]
You can try installing Python and the Python dependencies using conda.

**Comment by Soumi7** [comment]
I updated matplotlib version to 3.2.1. Error persists.

**Comment by Soumi7** [comment]
Does this mean the tests are successful? After running ```./bin/test```  this is the output:
```
 tests finished: 8937 passed, 279 skipped, 375 expected to fail, 
in 2688.47 seconds 
```

**Comment by Soumi7** [comment]
This is the issue when i type : ```git push github branch1```

```
(sympy-dev-py35) soumi@soumi-ganesh:~/sympy$ git push github branch1
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Soumi7** [comment]
Can you check this out? I dont know why the build fails.

https://travis-ci.org/github/sympy/sympy/builds/687496608

**Comment by asmeurer** [comment]
Yes. It would say that tests failed if there were errors.

**Comment by Soumi7** [comment]
I have made a PR for this issue. 

https://github.com/sympy/sympy/pull/19334

**Comment by Soumi7** [comment]
Umm has anyone checked out the PR I made?

**Comment by asmeurer** [comment]
In the future, mention in your pull request that it is related to GSoD so that it hits my email filters.

**Comment by Soumi7** [comment]
Most docstrings in the functions module do not adhere to lauren glattly's styling guide. 

I want to start updating the docstrings in Trigonometric Submodules. Should I create an issue for that?

**Comment by asmeurer** [comment]
Let's use #19591 as the issue to track all the documentation updates, so that we don't have separate issues for every module.

**Comment by Soumi7** [comment]
#19753
