### ISSUE TITLE
SymPy cannot be imported in master Python 2

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#17999]
```py
>>> import sympy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/__init__.py", line 64, in <module>
    from .concrete import *
  File "sympy/concrete/__init__.py", line 2, in <module>
    from .summations import summation, Sum
  File "sympy/concrete/summations.py", line 3, in <module>
    from sympy.calculus.singularities import is_decreasing
  File "sympy/calculus/__init__.py", line 4, in <module>
    from .singularities import (singularities, is_increasing,
  File "sympy/calculus/singularities.py", line 21, in <module>
    from sympy.solvers.solveset import solveset
  File "sympy/solvers/__init__.py", line 11, in <module>
    from .solvers import solve, solve_linear_system, solve_linear_system_LU, \
  File "sympy/solvers/solvers.py", line 542
SyntaxError: Non-ASCII character '\xe2' in file sympy/solvers/solvers.py on line 543, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

It looks like #17921 added an em dash to some docstrings. Those should be replaced with `-`. 

More importantly, we should figure out why Travis did not catch this. 

This would have been caught by https://github.com/sympy/sympy/pull/16272. I guess it is necessary, since we can't rely on Python 2 imports failing in Travis. And in Python 3, the imports won't fail at all, but we should still avoid such Unicode characters in the source.

**Comment by asmeurer** [comment]
There are other issues in master as well as 1.5, which #17921 can find. For instance, test_pickling.py has a non-breaking space. It isn't detected because it isn't ever imported directly (I guess the test runner opens it in utf-8 mode so it doesn't cause a problem).

**Comment by asmeurer** [comment]
pytest fails though. We should maybe make the test runner use `tokenize.detect_encoding` instead of forcing utf-8 everywhere (although that's a moot point once we drop Python 2). Really, we just need #16272.

**Comment by oscarbenjamin** [comment]
I still think that after dropping Python 2 we should be careful about including non-ASCII characters in the codebase.

**Comment by asmeurer** [comment]
I now get

```
SyntaxError: Non-ASCII character '\xc2' in file sympy/solvers/ode.py on line 1596, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

I would suggest merging in #16272 to make sure all the issues are found.

**Comment by oscarbenjamin** [comment]
Which branch did you test? The fix was merged into 1.5 rather than master. I can import sympy from Python 2.7 on the SymPy 1.5 branch. That will be merged into master later.

**Comment by asmeurer** [comment]
I just tested merging the latest version of @sylee957's branch into 1.5 and also with master and get no errors in either. So I guess the errors are fixed in his branch, which is why I think it would be useful to merge it into the release branch. 1.5 does import for me, but errors in test files don't show up from that because they aren't imported with `import sympy`. 

The ode error is still in master. It seems to have come from 8d9f441d28a8839be6ae803fce8e751f2d3ad8f9. which I don't think is in 1.5. You might check what you are doing that is creating non-breaking spaces after comment characters.

**Comment by oscarbenjamin** [comment]
I'm not sure how the nbsp got there. I'm also not sure why import sympy works in Travis.

I'll take a look at #16272

**Comment by oscarbenjamin** [comment]
The reason these errors aren't picked up on Travis is because `compileall` doesn't pick them up so with 2.7 if you do:
```
$ python -We:invalid -We::SyntaxWarning -m compileall -f -q sympy/
$ python -c import sympy
```
then both commands will complete successfully. By the time you try to import sympy it will load from the pyc files created by compileall.

**Comment by oscarbenjamin** [comment]
Maybe we should begin the test suite with
```
$ python -We:invalid -We::SyntaxWarning -c import sympy
```
