### ISSUE TITLE
PyPy travis failures

### ISSUE THREAD

**Issue by jcrist** [sympy/sympy#8972]
The tests in PyPy are failing for a couple tests. Mostly in combinatorics/permutations stuff. I'm 99% certain that this has to do with the [ordered dicts by default](http://morepypy.blogspot.com/2015/01/faster-more-memory-efficient-and-more.html) change in PyPy. This means that dicts that are key-value consistent are not _equlivalent_ due to ordering.

Example: https://travis-ci.org/sympy/sympy/jobs/49694978

**Comment by jcrist** [comment]
Actually, not all failures are the same, some fail on other tests that aren't comparing dicts on output. I think this still has to do with the dict implementation messing with internals, but I could be wrong.

**Comment by moorepants** [comment]
Duplicate: https://github.com/sympy/sympy/issues/8949

**Comment by jcrist** [comment]
Woops, you're right. I did a quick scan of the issues before filing, and didn't see that one. My mistake.

**Comment by jcrist** [comment]
Actually, that issue was closed by @smichr , while we're still clearly having travis failures. I'm leaving this open.

**Comment by aktech** [comment]
@jcrist 
I think, duplicate label can also be removed.

**Comment by smichr** [comment]
The auto-close feature closed this; I should not have said that it fixed all of the problems. I list the two remaining tests that fail there and repeat them here:

https://travis-ci.org/smichr/sympy/jobs/49777907
https://travis-ci.org/smichr/sympy/jobs/49777910

**Comment by toolforger** [comment]
I just completed some local testing.

pypy 2.4.0 runs fine, no failures or errors.

pypy 2.5.0 (newly released on Feb 2 I think) gives me these:
sympy/solvers/tests/test_ode.py", line 112, in test_linear_2eq_order2
sympy/polys/tests/test_factortools.py", line 531, in test_dup_factor_list
sympy/polys/tests/test_factortools.py", line 636, in test_dmp_factor_list
sympy/solvers/tests/test_ode.py", line 681, in test_classify_sysode

Comparing with what @smichr saw gives me considerable overlap and considerable differences:
sympy/combinatorics/util.py", line 337, in sympy.combinatorics.util._remove_gens
sympy/polys/tests/test_factortools.py", line 531, in test_dup_factor_list
sympy/polys/tests/test_factortools.py", line 636, in test_dmp_factor_list

(Heads-up for those using pythonz: saghul just added pypy 2.5.0, update your pythonz installations to do local testing with pypy 2.5.)

**Comment by jksuom** [comment]
From python docs:
> CPython implementation detail: Keys and values are listed in an arbitrary order which is
> non-random, varies across Python implementations, and depends on the dictionary’s history of
>  insertions and deletions.

Apparently this is also valid in pypy. `items()`,  `keys()` and `values()` are not returned in the same order as in standard python.
The assertion error in the factor list test derives from `factors[0][0].almosteq(f, 1e-10)`. It can be fixed:
```
--- a/sympy/polys/rings.py
+++ b/sympy/polys/rings.py
@@ -632,13 +632,13 @@ def almosteq(p1, p2, tolerance=None):
         ring = p1.ring
 
         if isinstance(p2, ring.dtype):
-            if list(p1.keys()) != list(p2.keys()):
+            if set(p1.keys()) != set(p2.keys()):
                 return False
 
             almosteq = ring.domain.almosteq
 
-            for c1, c2 in zip(p1.itercoeffs(), p2.itercoeffs()):
-                if not almosteq(c1, c2, tolerance):
+            for k in p1.keys():
+                if not almosteq(p1[k], p2[k], tolerance):
                     return False
             else:
                 return True
```

The failure in sympy/combinatorics/util.py appears to be caused by the nondeterministic nature of the incremental Schreier-Sims algorithm. Different implementations give diverging results after the
line 2529 in sympy/combinatorics/perm_groups.py:
```
             for beta, u_beta in list(transversals[i].items()):
```
The best way to fix the example is probably giving `base` and `strong_gens` explicitly.

**Comment by toolforger** [comment]
The pypy 2.5.0 release notes claim otherwise:

> This makes ordered dicts the default dictionary implementation in RPython and in PyPy. [...]
> Note: Python programs can rely on the guaranteed dict order in PyPy now, but for compatibility with other Python implementations they should still use collections.OrderedDict where that really matters. Also, support for reversed() was not added to the ‘dict’ class; use OrderedDict.

I think we haven't fully understood what's happening yet.
At least I'm thoroughly confused right now...

**Comment by AadityaNair** [comment]
Will an element-by-element comparison fix the issue ?

**Comment by toolforger** [comment]
I'd want to avoid element-by-element comparison.
First, it is going to be slower than a direct equality test.
Second, it's not going to help us understand why the key orders have started to diverge.
Third, since we don't understand what causes the divergence, it may or may not help.

**Comment by smichr** [comment]
@toolforger , can this be closed now that #8972 has been merged?

**Comment by toolforger** [comment]
Did somebody run the tests locally? Including doctests and slow tests?
I wasn't aware of the patch, I added comments there.

**Comment by toolforger** [comment]
Local testing still reveals errors:

```
____________ sympy/solvers/tests/test_ode.py:test_linear_2eq_order2 ____________
  File "/home/jo/Projekte/sympy-workspace/sympy-project/sympy/sympy/solvers/tests/test_ode.py", line 112, in test_linear_2eq_order2
    assert dsolve(eq3) == sol3
  File "sympy/solvers/ode.py", line 613, in dsolve
    sols = solvefunc(match)
  File "sympy/solvers/ode.py", line 6811, in sysode_linear_2eq_order2
    sol = _linear_2eq_order2_type9(x, y, t, r)
  File "sympy/solvers/ode.py", line 7320, in _linear_2eq_order2_type9
    [k1, k2, k3, k4] = roots_quartic(Poly(eq))
  File "sympy/polys/polyroots.py", line 290, in roots_quartic
    _, a, b, c, d = f.monic().all_coeffs()
ValueError: expected length 5, got 2

________________________________________________________________________________
_____________ sympy/solvers/tests/test_ode.py:test_classify_sysode _____________
  File "/home/jo/Projekte/sympy-workspace/sympy-project/sympy/sympy/solvers/tests/test_ode.py", line 681, in test_classify_sysode
    assert classify_sysode(eq2) == sol2
AssertionError

 tests finished: 5737 passed, 1 failed, 178 skipped, 333 expected to fail, 
3 expected to fail but passed, 1 exceptions, in 4247.95 seconds 
DO *NOT* COMMIT!
```

**Comment by toolforger** [comment]
Local doctests run fine with pypy 2.5.
AFAIK there are no Travis exclusions in the docstring code so that's what I expected.

**Comment by toolforger** [comment]
Slow tests just finished.
I'm just seeing the kane3 test failing with the usual complaint about deprecated API use.

**Comment by toolforger** [comment]
I did some debugging and *suspect* it is related to ```classify_sysode()``` in ```sympy.solvers.ode```.
I'm seeing it return multiple values, some of them lists, and some of them dicts, and calling code assuming that dict order and list order are in some way related (which they are not by Python semantics, and only happen to work in CPython but not anymore in pypy).

So I think the semantics of ```classify_sysode```'s return value should be fixed to not rely on dict order anymore. (Fortunately, it's just a single call in SymPy; unfortunately, there are 28 unit tests and 2 doctests for it.)

**Comment by toolforger** [comment]
I take my words back: After reading the code and rewriting the docstring into something less vague, the data returned do not depend on any dict order per se. (The return value is a big karmic burden on somebody's soul though; this whole "return-stuff-as-a-dict" concept just screams for being recast as a class.)
There's still some dict order dependency going on in the ODE code though: I'm still seeing a flipped sign.

**Comment by smichr** [comment]
> Did somebody run the tests locally?

The tests of #9033 pass. Is there something that is still not passing locally?

**Comment by toolforger** [comment]
I'm having issues with test_classify_sysode.
Also, I do not think that the true cause of the test failures has been found, I suspect we're fixing symptoms.
I'm trying to find that out, but I'm having trouble understanding what the ODE code does. Is there anybody whom I could ask about details of that code? @KDMOE (Kundan Kumar, author of that code) does not seem to be around anymore.

**Comment by smichr** [comment]
It is likely patterned after @asmeurer 's work, so he would be a good one to ask.

**Comment by toolforger** [comment]
All the patches I'm seeing mentioned here are replacing fast, C-based dictionary comparisons with slower bytecode loops.
They're replacing fast, C-based dictionary comparisons with slower bytecode loops.
Worse, they're fixing symptoms (dictionaries with have a diverged order) instead of fixing the cause, which we haven't even found yet. We *assume* it's orders that diverge between dictionary keys and some list, but *we have not identified that yet*, and even if tests now pass, we cannot be sure that we have fixed the true problem. Most likely some internal code is still written with horribly wrong assumptions in mind, making it harder to maintain it in the future.

I'm -1 about all these patches.
Let's find the true cause first.

**Comment by rlamy** [comment]
AFAICT, the issue here is that the original code relied on an unreliable quirk of the CPython and PyPy<=2.4 implementations of dict: elements are put into buckets based on the least significant bits of the hashes of the keys. If there are no collisions, `dct.keys()` then comes out ordered according to `hash(key) % n` where n is 8 for a small dict (less than 6? elements). In particular, if the keys are integers in the range 0 to 7, then `dct.keys()` appears to be sorted according to the values of the keys. 

I suspect that the ode code relied on that somehow, while the polynomial code clearly expected dict ordering to be independent of insertion order.

**Comment by toolforger** [comment]
I'm seeing so much. I have done some debugging and am seeing a sign in an expression that's + in CPython and - in PyPy. It's slow going though, I'm having trouble distinguishing relevant from irrelevant differences because I don't know what the ODE code is supposed to do.

**Comment by ylemkimon** [comment]
```
________________________________________________________________________________
______ sympy/combinatorics/tests/test_perm_groups.py:test_minimal_blocks _______
  File "/home/travis/.venv/site-packages/sympy/combinatorics/tests/test_perm_groups.py", line 465, in test_minimal_blocks
    assert P.minimal_blocks() == [[0, 3, 0, 3, 0, 3], [0, 4, 5, 0, 4, 5]]
AssertionError
```

and

```
________________________________________________________________________________
_______ sympy.combinatorics.perm_groups.PermutationGroup.minimal_blocks ________
File "/home/travis/.venv/site-packages/sympy/combinatorics/perm_groups.py", line 1896, in sympy.combinatorics.perm_groups.PermutationGroup.minimal_blocks
Failed example:
    DihedralGroup(6).minimal_blocks()
Expected:
    [[0, 3, 0, 3, 0, 3], [0, 4, 2, 0, 4, 2]]
Got:
    [[0, 5, 0, 5, 0, 5], [0, 4, 2, 0, 4, 2]]
```

which are introduced in #13104, fails on PyPy. @valglad

**Comment by valglad** [comment]
@ylemkimon The answer in the second case is still correct. The block representatives seem to have changed, but it's not a problem. I suspect the first error is for the same reason.

Either I could change how it's tested so that it's more general, or add a couple of lines to `minimal_block` to rewrite a block system after it's found so that the representative is always minimal. I suppose I could do that latter.

**Comment by oscarbenjamin** [comment]
Is this still an issue?

I don't see PyPy tests failing often now (2 years since last comment in this thread)

**Comment by asmeurer** [comment]
PyPy tests are in allowed failures, so you wouldn't notice the failures unless you looked at the logs. But I also haven't seen any failures in a while (they are only allowed failure because the PyPy download fails sometimes). I recall several of these issues being fixed (see the xrefed PRs).

Let's close this. If there are any failures in a PyPy test, we should open a new issue.
